/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    pieces: Piece;
    media: Media;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    pieces: PiecesSelect<false> | PiecesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    homepage: Homepage;
    'site-settings': SiteSetting;
    legal: Legal;
  };
  globalsSelect: {
    homepage: HomepageSelect<false> | HomepageSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    legal: LegalSelect<false> | LegalSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Der Katalog der Unikate. Die Reihenfolge (Drag & Drop) bestimmt die Reihenfolge im Katalog und im Hero.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pieces".
 */
export interface Piece {
  id: number;
  _order?: string | null;
  name: string;
  /**
   * Wird für die Detail-Seite verwendet: /unikate/<slug>.
   */
  slug: string;
  category: 'Ringe' | 'Ohrschmuck' | 'Halsschmuck' | 'Armschmuck' | 'Broschen';
  image: number | Media;
  material: string;
  dimensions?: string | null;
  stone?: string | null;
  carat?: string | null;
  surface?: string | null;
  price: string;
  provenance: 'real' | 'illustrative';
  inHero?: boolean | null;
  heroImage?: (number | null) | Media;
  heroShortName?: string | null;
  heroSpec?: string | null;
  heroObjectPosition?: string | null;
  heroTint?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'pieces';
        value: number | Piece;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pieces_select".
 */
export interface PiecesSelect<T extends boolean = true> {
  _order?: T;
  name?: T;
  slug?: T;
  category?: T;
  image?: T;
  material?: T;
  dimensions?: T;
  stone?: T;
  carat?: T;
  surface?: T;
  price?: T;
  provenance?: T;
  inHero?: T;
  heroImage?: T;
  heroShortName?: T;
  heroSpec?: T;
  heroObjectPosition?: T;
  heroTint?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage".
 */
export interface Homepage {
  id: number;
  hero?: {
    eyebrow?: string | null;
    headline?: string | null;
    ctaPrimary?: string | null;
    ctaSecondary?: string | null;
    hoursShort?: string | null;
    footnote?: string | null;
  };
  zweifarbigkeit?: {
    eyebrow?: string | null;
    heading?: string | null;
    paragraphs?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
    techniques?:
      | {
          name: string;
          text: string;
          id?: string | null;
        }[]
      | null;
    imageGold?: (number | null) | Media;
    imageKupfer?: (number | null) | Media;
    imageBand?: (number | null) | Media;
    bandCaptionLeft?: string | null;
    bandCaptionRight?: string | null;
  };
  unikate?: {
    eyebrow?: string | null;
    heading?: string | null;
    intro?: string | null;
    enquiry?: string | null;
  };
  werkstatt?: {
    eyebrow?: string | null;
    heading?: string | null;
    intro?: string | null;
    steps?:
      | {
          title: string;
          text: string;
          id?: string | null;
        }[]
      | null;
    quote?: string | null;
    quoteAttribution?: string | null;
    imageWerkbank?: (number | null) | Media;
    imageHaende?: (number | null) | Media;
  };
  meisterin?: {
    eyebrow?: string | null;
    heading?: string | null;
    paragraphs?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
    image?: (number | null) | Media;
    imageCaptionLeft?: string | null;
    imageCaptionRight?: string | null;
    stats?:
      | {
          value: string;
          label: string;
          id?: string | null;
        }[]
      | null;
  };
  eheringe?: {
    eyebrow?: string | null;
    heading?: string | null;
    intro?: string | null;
    steps?:
      | {
          title: string;
          text: string;
          id?: string | null;
        }[]
      | null;
    ctaLabel?: string | null;
    imagePair?: (number | null) | Media;
    imageDetail?: (number | null) | Media;
  };
  besuch?: {
    eyebrow?: string | null;
    heading?: string | null;
    phoneEyebrow?: string | null;
    hoursHeading?: string | null;
    image?: (number | null) | Media;
    imageCaptionLeft?: string | null;
    imageCaptionRight?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  meta?: {
    title?: string | null;
    description?: string | null;
  };
  atelier?: {
    name?: string | null;
    shortName?: string | null;
    legalName?: string | null;
    owner?: string | null;
    ownerTitle?: string | null;
    street?: string | null;
    zip?: string | null;
    city?: string | null;
    district?: string | null;
    phoneDisplay?: string | null;
    phoneHref?: string | null;
    email?: string | null;
    mapsUrl?: string | null;
    mapsEmbedUrl?: string | null;
  };
  navLinks?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  timeline?:
    | {
        year: string;
        event: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Reihenfolge = Anzeigereihenfolge. Öffnung von/bis in Minuten ab Mitternacht (z.B. 600 = 10:00, 1080 = 18:00) treibt die „Jetzt geöffnet“-Anzeige; für „nach Vereinbarung“/geschlossen leer lassen.
   */
  hours?:
    | {
        weekday: number;
        day: string;
        time: string;
        openStart?: number | null;
        openEnd?: number | null;
        id?: string | null;
      }[]
    | null;
  hoursNote?: string | null;
  footer?: {
    strapline?: string | null;
    hoursSummary?:
      | {
          days: string;
          time: string;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "legal".
 */
export interface Legal {
  id: number;
  impressumTitle?: string | null;
  impressum?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  datenschutzTitle?: string | null;
  datenschutz?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage_select".
 */
export interface HomepageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        eyebrow?: T;
        headline?: T;
        ctaPrimary?: T;
        ctaSecondary?: T;
        hoursShort?: T;
        footnote?: T;
      };
  zweifarbigkeit?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        paragraphs?:
          | T
          | {
              text?: T;
              id?: T;
            };
        techniques?:
          | T
          | {
              name?: T;
              text?: T;
              id?: T;
            };
        imageGold?: T;
        imageKupfer?: T;
        imageBand?: T;
        bandCaptionLeft?: T;
        bandCaptionRight?: T;
      };
  unikate?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        intro?: T;
        enquiry?: T;
      };
  werkstatt?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        intro?: T;
        steps?:
          | T
          | {
              title?: T;
              text?: T;
              id?: T;
            };
        quote?: T;
        quoteAttribution?: T;
        imageWerkbank?: T;
        imageHaende?: T;
      };
  meisterin?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        paragraphs?:
          | T
          | {
              text?: T;
              id?: T;
            };
        image?: T;
        imageCaptionLeft?: T;
        imageCaptionRight?: T;
        stats?:
          | T
          | {
              value?: T;
              label?: T;
              id?: T;
            };
      };
  eheringe?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        intro?: T;
        steps?:
          | T
          | {
              title?: T;
              text?: T;
              id?: T;
            };
        ctaLabel?: T;
        imagePair?: T;
        imageDetail?: T;
      };
  besuch?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        phoneEyebrow?: T;
        hoursHeading?: T;
        image?: T;
        imageCaptionLeft?: T;
        imageCaptionRight?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  meta?:
    | T
    | {
        title?: T;
        description?: T;
      };
  atelier?:
    | T
    | {
        name?: T;
        shortName?: T;
        legalName?: T;
        owner?: T;
        ownerTitle?: T;
        street?: T;
        zip?: T;
        city?: T;
        district?: T;
        phoneDisplay?: T;
        phoneHref?: T;
        email?: T;
        mapsUrl?: T;
        mapsEmbedUrl?: T;
      };
  navLinks?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  timeline?:
    | T
    | {
        year?: T;
        event?: T;
        id?: T;
      };
  hours?:
    | T
    | {
        weekday?: T;
        day?: T;
        time?: T;
        openStart?: T;
        openEnd?: T;
        id?: T;
      };
  hoursNote?: T;
  footer?:
    | T
    | {
        strapline?: T;
        hoursSummary?:
          | T
          | {
              days?: T;
              time?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "legal_select".
 */
export interface LegalSelect<T extends boolean = true> {
  impressumTitle?: T;
  impressum?: T;
  datenschutzTitle?: T;
  datenschutz?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}